In [7]:
pip install kaggle

Requirement already satisfied: kaggle in c:\users\sasik\anaconda3\lib\site-packages (1.6.17)
Requirement already satisfied: six>=1.10 in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (4.66.5)
Requirement already satisfied: python-slugify in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in c:\users\sasik\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\sasik\anaconda3\lib\site-packages (from bleach->kaggle) (24.1)
Requirement already satisfied: webencodings in c:\users\sasik\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\sasik\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sasik\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sasik\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\sasik\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [23]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\sasik

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 233kB/s]
100%|##########| 200k/200k [00:00<00:00, 232kB/s]

In [8]:
import shutil

# Specify the zip file and the output directory
zip_file_path = r"C:\Users\sasik\orders.csv.zip"  # Path to the ZIP file
extract_to = r"C:\Users\sasik\orders"  # Folder where files will be extracted

# Extract the ZIP file
shutil.unpack_archive(zip_file_path, extract_to)

In [11]:
import pandas as pd

In [13]:
pd.read_csv(r'C:\Users\sasik\orders\orders.csv')

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [15]:
df = pd.read_csv(r'C:\Users\sasik\orders\orders.csv')

In [17]:
df.isnull()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9990,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9993,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           1
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [21]:
df_new = df.dropna()

In [23]:
df_new.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           0
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [25]:
df_new

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [27]:
df_renamed = df_new.rename(columns={"Order Id": "order_id", "Order Date": "order_date","Ship Mode":"ship_mode","Segment":"segment","Country":"country","City":"city","State":"state","Postal Code":"postal_code","Region":"region","Category":"category","Sub Category":"sub_category","Product Id":"product_id","cost price":"cost_price","List Price":"list_price","Quantity":"quantity","Discount Percent":"discount_percent"})

In [29]:
df_renamed

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [55]:
df = df_renamed.applymap(lambda x: x.strip() if isinstance(x, str) else x)

C:\Users\sasik\AppData\Local\Temp\ipykernel_20304\46010987.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df_renamed.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [31]:
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [47]:
df=df_renamed

In [49]:
df["discount"] = (df["list_price"] * df["discount_percent"]) / 100

df["sale_price"] = df["list_price"] - df["discount"]

df["profit"] = df["sale_price"] - df["cost_price"]
print(df)

      order_id  order_date       ship_mode    segment        country  \
0            1  2023-03-01    Second Class   Consumer  United States
1            2  2023-08-15    Second Class   Consumer  United States
2            3  2023-01-10    Second Class  Corporate  United States
3            4  2022-06-18  Standard Class   Consumer  United States
4            5  2022-07-13  Standard Class   Consumer  United States
...        ...         ...             ...        ...            ...
9989      9990  2023-02-18    Second Class   Consumer  United States
9990      9991  2023-03-17  Standard Class   Consumer  United States
9991      9992  2022-08-07  Standard Class   Consumer  United States
9992      9993  2022-11-19  Standard Class   Consumer  United States
9993      9994  2022-07-17    Second Class   Consumer  United States

                 city       state  postal_code region         category  \
0           Henderson    Kentucky        42420  South        Furniture
1           Henderson    Kentucky        42420  South        Furniture
2         Los Angeles  California        90036   West  Office Supplies
3     Fort Lauderdale     Florida        33311  South        Furniture
4     Fort Lauderdale     Florida        33311  South  Office Supplies
...               ...         ...          ...    ...              ...
9989            Miami     Florida        33180  South        Furniture
9990       Costa Mesa  California        92627   West        Furniture
9991       Costa Mesa  California        92627   West       Technology
9992       Costa Mesa  California        92627   West  Office Supplies
9993      Westminster  California        92683   West  Office Supplies

     sub_category       product_id  cost_price  list_price  quantity  \
0       Bookcases  FUR-BO-10001798         240         260         2
1          Chairs  FUR-CH-10000454         600         730         3
2          Labels  OFF-LA-10000240          10          10         2
3          Tables  FUR-TA-10000577         780         960         5
4         Storage  OFF-ST-10000760          20          20         2
...           ...              ...         ...         ...       ...
9989  Furnishings  FUR-FU-10001889          30          30         3
9990  Furnishings  FUR-FU-10000747          70          90         2
9991       Phones  TEC-PH-10003645         220         260         2
9992        Paper  OFF-PA-10004041          30          30         4
9993   Appliances  OFF-AP-10002684         210         240         2

      discount_percent  discount  sale_price  profit
0                    2       5.2       254.8    14.8
1                    3      21.9       708.1   108.1
2                    5       0.5         9.5    -0.5
3                    2      19.2       940.8   160.8
4                    5       1.0        19.0    -1.0
...                ...       ...         ...     ...
9989                 4       1.2        28.8    -1.2
9990                 4       3.6        86.4    16.4
9991                 2       5.2       254.8    34.8
9992                 3       0.9        29.1    -0.9
9993                 3       7.2       232.8    22.8

[9993 rows x 19 columns]

In [51]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [53]:
df.to_csv(r"C:\Users\sasik\orders\Result.csv", index=False)

In [ ]:
Result

In [85]:
df1 = df[["order_id"] + list(df.columns[1:10])]

In [87]:
df1

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies
...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies

In [89]:
df1.to_csv(r"C:\Users\sasik\orders\df1_orders.csv", index=False)

In [77]:
df2 = df[["order_id"] + list(df.columns[10:20])]

In [79]:
df2

,order_id,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...
9989,9990,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [81]:
df2.to_csv(r"C:\Users\sasik\orders\df2_orders.csv", index=False)

In [83]:
df2

,order_id,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...
9989,9990,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8